# 单机
server:
  port: 8761 # eureka 默认端口8761
spring:
  application:
    name: eureka-server # 应用名称 不要使用特殊字符
# eureka 可以对 server client 实例 进行配置
# 在服务端一般对 server与实例进行配置
eureka:
  server:
    renewal-percent-threshold: 0.85  # 续约百分比 当超过这个值的应用没有与服务端进行续约, 则服务端不会剔除任何一个应用
    eviction-interval-timer-in-ms: 10000 # 多长时间进行定期删除操作
  client:
    register-with-eureka: false
  instance:
    hostname: localhost # 主机名
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port} # 实例id
    prefer-ip-address: true # 以ip信息的形式显示服务信息
    lease-renewal-interval-in-seconds: 5 # 服务实例的续约时间（一般要小于服务端进行定期删除的时间, 可以为 1/2）
