server:
  port: 10086
spring:
  application:
    name: hystrix-feign-project-admin-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        # 暴露所有的监控端点 默认暴露 health, info
        include: '*'