server:
    port: 80
spring:
    application:
        name: nacos-gateway
    cloud:
        nacos:
            # nacos服务所在地址 不填写contextPath
            # 单机注册
            #      server-addr: localhost:8848
            # 集群注册
            server-addr: localhost:8841,localhost:8843,localhost:8845
            username: nacos
            password: nacos
            discovery:
                namespace: 4fb7b1c2-e9fc-4665-b176-5915d4e1530a
                group: A_GROUP
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
