server:
  port: ${PORT:8761}
spring:
  application:
    name: eureka-server
eureka:
  server:
    eviction-interval-timer-in-ms: 10000
  client:
    service-url: # 如果不进行指定 默认会向 http://localhost:8761/eureka 进行注册
      # 要同时注册到多个注册中心, 将注册中心的地址使用逗号分隔
      # 因为 service-url 是以Map的形式进行的存储, 所以defaultZone不可以被替换成default-zone
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: ${PREFER_IP_ADDRESS:true}
    lease-renewal-interval-in-seconds: 5
    hostname: ${HOSTNAME:localhost}


