server:
  port: 8080
spring:
  application:
    name: hystrix-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
feign:
  hystrix:
    # 开启hystrix熔断器
    enabled: true