# 启动时动态指定server.port与eureka.instance.hostname 即可做到一个项目启动多个实例组成集群
server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  server:
    eviction-interval-timer-in-ms: 10000
  client:
    service-url: # 如果不进行指定 默认会向 http://localhost:8761/eureka 进行注册
      # 要同时注册到多个注册中心, 将注册中心的地址使用逗号分隔
      # 因为 service-url 是以Map的形式进行的存储, 所以defaultZone不可以被替换成default-zone
      defaultZone: http://node1.eureka:8761/eureka, http://node2.eureka:8762/eureka, http://node3.eureka:8763/eureka
  instance:
    # eureka集群需要 eureka-server 运行在不同机器上, 现在使用hosts进行映射, 来欺骗eureka
    # 在hosts中添加
    # 127.0.0.1 node1.eureka
    # 127.0.0.1 node2.eureka
    # 127.0.0.1 node3.eureka
    hostname: node1.eureka
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5

