server:
  port: 82
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: login-server-route
          uri: http://localhost:8081
          predicates:
            - Path=/login
      discovery:
        locator:
          # 关闭动态路由（测试网关集群）
          enabled: false
          # 服务名使用小写
          lower-case-service-id: true